on: [push, pull_request]

name: CI

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      rust_version: ${{ steps.read_toolchain.outputs.rust_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Read rust version"
        id: read_toolchain
        run: echo "rust_version=$(cat rust-version)" >> $GITHUB_OUTPUT

  build-check:
    needs: prepare
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - version: ${{ needs.prepare.outputs.rust_version }}
          - version: 1.63.0 # Overall MSRV
          - version: 1.75.0 # Specific MSRV for `bdk_electrum`
        features:
          - --no-default-features --features miniscript/no-std
          - --all-features
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ matrix.rust.version }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Pin dependencies for 1.75
        if: matrix.rust.version == '1.75.0'
        run: |
          cargo update -p home --precise "0.5.9"
      - name: Pin dependencies for MSRV
        if: matrix.rust.version == '1.63.0'
        run: ./ci/pin-msrv.sh
      - name: Build + Check
        run: |
          if [ "${{matrix.rust.version}}" = '1.63.0' ]; then
            cargo build --workspace --exclude 'example_*' --exclude 'bdk_electrum' ${{ matrix.features }}
            cargo check --workspace --exclude 'example_*' --exclude 'bdk_electrum' ${{ matrix.features }}
          else
            cargo build --workspace --exclude 'example_*' ${{ matrix.features }}
            cargo check --workspace --exclude 'example_*' ${{ matrix.features }}
          fi

  test-bdk:
    needs: prepare
    name: Test Bdk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - version: ${{ needs.prepare.outputs.rust_version }}
          - version: 1.63.0 # MSRV
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ matrix.rust.version }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Pin dependencies for MSRV
        if: matrix.rust.version == '1.63.0'
        run: ./ci/pin-msrv.sh
      - name: Test library
        run: |
          cargo test -p bdk_core --all-features
          cargo test -p bdk_chain --all-features
          cargo test -p bdk_bitcoind_rpc --all-features -- --test-threads=2
          cargo test -p bdk_esplora --all-features -- --test-threads=2
          cargo test -p bdk_file_store --all-features
          cargo test -p bdk_testenv --all-features -- --test-threads=2
          cargo test -p bdk_wallet --all-features

  test-electrum:
    needs: prepare
    name: Test Electrum
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - version: ${{ needs.prepare.outputs.rust_version }}
          - version: 1.75.0 # MSRV
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ matrix.rust.version }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Pin dependencies for MSRV
        if: matrix.rust.version == '1.75.0'
        run: |
          cargo update -p home --precise "0.5.9"
      - name: Test electrum
        run: cargo test -p bdk_electrum --all-features -- --test-threads=2
        
  check-no-std:
    needs: prepare
    name: Check no_std
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ needs.prepare.outputs.rust_version }}
          # targets: "thumbv6m-none-eabi"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Check bdk_chain
        working-directory: ./crates/chain
        # TODO "--target thumbv6m-none-eabi" should work but currently does not
        run: cargo check --no-default-features --features miniscript/no-std,hashbrown
      - name: Check bdk wallet
        working-directory: ./crates/wallet
        # TODO "--target thumbv6m-none-eabi" should work but currently does not
        run: cargo check --no-default-features --features miniscript/no-std,bdk_chain/hashbrown
      - name: Check esplora
        working-directory: ./crates/esplora
        # TODO "--target thumbv6m-none-eabi" should work but currently does not
        run: cargo check --no-default-features --features miniscript/no-std

  check-wasm:
    needs: prepare
    name: Check WASM
    runs-on: ubuntu-20.04
    env:
      CC: clang-10
      CFLAGS: -I/usr/include
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install a recent version of clang that supports wasm32
      - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - || exit 1
      - run: sudo apt-get update || exit 1
      - run: sudo apt-get install -y libclang-common-10-dev clang-10 libc6-dev-i386 || exit 1
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ needs.prepare.outputs.rust_version }}
            targets: "wasm32-unknown-unknown"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Check bdk wallet
        working-directory: ./crates/wallet
        run: cargo check --target wasm32-unknown-unknown --no-default-features --features miniscript/no-std,bdk_chain/hashbrown
      - name: Check esplora
        working-directory: ./crates/esplora
        run: cargo check --target wasm32-unknown-unknown --no-default-features --features async,miniscript/no-std

  fmt:
    needs: prepare
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ needs.prepare.outputs.rust_version }}
            components: rustfmt
      - name: Check fmt
        run: cargo fmt --all -- --config format_code_in_doc_comments=true --check

  clippy_check:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ needs.prepare.outputs.rust_version }}
            components: clippy
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings

  build-examples:
    needs: prepare
    name: Build & Test Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-dir:
          - example_cli
          - example_bitcoind_rpc_polling
          - example_electrum
          - example_esplora
          - example_wallet_electrum
          - example_wallet_esplora_async
          - example_wallet_esplora_blocking
          - example_wallet_rpc
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ needs.prepare.outputs.rust_version }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Build
        working-directory: example-crates/${{ matrix.example-dir }}
        run: cargo build
